### ISSUE TITLE
ติดตั้ง Gitlab ไว้ใช้ใน ออฟฟิศ

### ISSUE THREAD

**Issue by M4R14** [M4R14/note#2]
# ติดตั้ง Gitlab ไว้ใช้ใน ออฟฟิศ
เมื่อ GitHub เริ่มเริ่มมาถึงทางตัน (เปลื่องตังนั้นเอง) ทีมเราก็มี Programmer เพิ่มขึ้น และยังมี Freelance อีก ผมพยายามมองหาอะไรที่มันคุ่มค่ากว่า และไม่รู้ นรกชังหรือสวรรค์แกล้ง ผมเลือก GitLab

ผมมี server อยู่แล้วมันรัน jenkins อยู่ แต่ยังพอจะใช้ได้ ที่เหลือก็แค่ติดตั้ง GitLab ผมใช้ติดตั้งมันโดยใช้ Docker เพราะถ้ามีปัญหาอะไร ก็แค่ Reset Docker ใหม่ส่ะ (jenkins ผมลงปกติตอนนี้พังไปล่ะ ยังไม่มีเวลาไปดใจมันเลย)

เริ่มต้นด้วย
สร้าง vim `docker-compose.yml`
```yml
version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    hostname: <hostname>
    environment:
      GITLAB_OMNIBUS_CONFIG: |
         gitlab_rails['smtp_enable'] = true
         gitlab_rails['smtp_address'] = "smtp.gmail.com"
         gitlab_rails['smtp_port'] = 587
         gitlab_rails['smtp_user_name'] = "<e-mail>"
         gitlab_rails['smtp_password'] = "<pass>""
         gitlab_rails['smtp_domain'] = "smtp.gmail.com"
         gitlab_rails['smtp_authentication'] = "login"
         gitlab_rails['smtp_enable_starttls_auto'] = true
         gitlab_rails['smtp_tls'] = false
         gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
         gitlab_rails['gitlab_shell_ssh_port'] = 5022
    ports:
      - '80:80'
      - '443:443'
      - '5022:22'
```
ผมใช้ mail ของ gmail จึง set up ไว้แบบนั้น

`<hostname>` ให้ระบบตรงมาตาม Domain ที่ใช้นางจริงๆไปเลย

ในนั้นผมยังเปิด port 80, 443, 5022 ตรงนี้ก็อย่าลืมไป `ufw allow <port>/<potocal>` ที่ server ให้เรียบร้อย ไม่เช่นนั้น เพื่อน Programmer เราจะใช้ Gitlab ไม่ได้เลย จะ push จะ pull ก็ไม่ได้

ผมสร้าง directory ไว้เก็บข้อมูลจาก GitLab ไว้ที่ `srv/gitlab` อย่างน้อยสิ่งที่ผม Set Up ไว้จะไม่ได้หายไปไหน จึงเพิ่ม volumes ไว้ตามนี้

```yml
    ...
    volumes:
        - ./srv/gitlab/logs:/var/log/gitlab
        - ./srv/gitlab/data:/var/opt/gitlab
```

### สุดท้าย
รันคำสั่ง docker-composer up จะนานหน่อยแหละ ประมาณ 5 นาทีได้ จะมีขั้นตอนการติดตั้งอะไรหน่อย ก็ตามน้ำไปนะ
